name: Damage Calculation Test

on:
  push:
    branches: [ main-2026 ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js v22.22.0
      uses: actions/setup-node@v4
      with:
        node-version: '22.22.0'
    
    - run: yarn install
    - run: yarn test
